### ISSUE TITLE
renderToNodeStream example

### ISSUE THREAD

**Issue by sayjeyhi** [theKashey/used-styles#17]
In Readme file you mentioned using of this Readable :
```javascript
// small utility for "readable" streams
const readable = () => {
  const s = new Readable();
  s._read = () => true;
  return s;
};
```
But there is no usage for this variable , is it correct?

**Comment by theKashey** [comment]
You can find MUCH simpler examples in this PR https://github.com/theKashey/used-styles/pull/16

**Comment by theKashey** [comment]
yep, it should be `readableString`, used later in the code.

**Comment by sayjeyhi** [comment]
@theKashey actually in [that example ](https://github.com/theKashey/used-styles/blob/a3c1c658cd093452ab77d319af904763d33e8716/README.md) `createStyleStream` first parameter is `htmlStream` but even in `2.1.1` version `createStyleStream` first argument is style definition !

**Comment by theKashey** [comment]
It sounds like I should extract examples out of the README to keep them type-able, and synchronize their content back the readme, so it would be always up-to-date. Not like it is right now :(
