### ISSUE TITLE
No dist in published package

### ISSUE THREAD

**Issue by lazysergey** [theKashey/used-styles#28]
hi, I tried to use this package in my project but I don't see `dist` directory in `node_modules/used-styles`, shouldn't it be published?

**Comment by theKashey** [comment]
It's definitely there - https://unpkg.com/browse/used-styles@2.1.4/dist/

**Comment by lazysergey** [comment]
thanks for reply 👍  just found the issue - I had wrong package name - as it's not specified in readme I supposed it should be `theKashey/used-styles`, maybe worth adding this to docs?

`yarn init -y && yarn add theKashey/used-styles` gives result below :(

https://user-images.githubusercontent.com/30532154/121684042-dde46400-cac6-11eb-9854-b66fea82740e.mov

**Comment by theKashey** [comment]
I will update readme and point in the right name to use, but... probably it's also very important to let you know that packages cannot exists in a way you tried to use - it's always `package` or `@scope/package`. Not `scope/package` - in this case you (probably) installing stuff from github directly.

Just never do it.
