### ISSUE TITLE
Make CLI

### ISSUE THREAD

**Issue by vovanezha** [theKashey/used-styles#3]
It will be great if you will add CLI for that tool

**Comment by theKashey** [comment]
Could you explain how it should work for your case?

**Comment by vovanezha** [comment]
For example, If I want to know which styles are unused I write something like `used-styles --path ./dist` in the console and get output in a new file or directly in console

**Comment by theKashey** [comment]
No. You don't get the point of the package - it reports which styles were used _right now_, when you have rendered _exactly this_ HTML.
There is no way it could scan/parse/tokenize source codes and figure out which styles were used, and which were not.
The best it could - try to find all the existing styles (as-is) in the sources, but that would not work well.

**Comment by vovanezha** [comment]
Hmm, okay, I got you. But we already have _Coverage_ tool directly in _Chrome DevTools_ that can show you what JS and CSS are unused at load and run time. Probably, you need to explain users why they should use your tool

**Comment by theKashey** [comment]
I thought that was clear from the readme and examples provided - to __send__ "used styles" to the browser during SSR.
That's more about code splitting and tracking which `.css` file should be sent to the browser if some `class` got used.

**Comment by vovanezha** [comment]
Oh, now I understood. But anyway, it's was unclear from the readme, at least for me

**Comment by theKashey** [comment]
Nobody perfect 🤷‍♂️
