### ISSUE TITLE
CSS truncated incorrectly 

### ISSUE THREAD

**Issue by Tonyhliu** [theKashey/used-styles#46]
Due to how our components stylesheets target svg classes for lottie player :

i.e. 
```
.-lottie-player svg path[fill="rgb(255,255,255)"] {
  fill: var(--color-background)
}
```

The resulting critical styles (from `getCriticalStyles`) gets truncated incorrectly like so : 
```
.lottie-lottie-player svg path[fill="rgb(255 { fill: var(--color-background); }
```

The expected style from the critical styles would be : 
```
.-lottie-player svg path[fill="rgb(255,255,255)"] {
  fill: var(--color-background)
}
```

**Comment by Tonyhliu** [comment]
@theKashey

**Comment by theKashey** [comment]
Got you. This moment is not actually under the direct control of used-styles as it used `post-css` to parse CSS and sounds like it's time for a long-delayed migration to postcss 8. That is quite likely to solve the problem.

**Comment by theKashey** [comment]
Try 2.5.0 - it should solve your problem

**Comment by Tonyhliu** [comment]
hey @theKashey - thanks for hopping on this so quickly, truly appreciate it. 

One quick note : did you happen to build the package before publishing? Noticing that I'm still getting the old version of the code, even though the package shows `2.5.0` 😅

**Comment by theKashey** [comment]
:duh: 2.5.2 should solve the probelm.

I've runned only tests relying on yarn hooks to build stuff before publish, but they are not working (again) for a some reason 😢

**Comment by Tonyhliu** [comment]
Haha no worries @theKashey - happens to the best of us 😅 

2.5.2 is working as expected, can't thank you enough for the quick turnaround time on this! Cheers m8!! 🥂
