### ISSUE TITLE
moveStyles module is not exposed anymore

### ISSUE THREAD

**Issue by hnrchrdl** [theKashey/used-styles#52]
Just upgraded from 2.1.3 to 2.6.0. It seems that imports from the moveStyles module are not exposed anymore.

Here is the culprit:

https://github.com/theKashey/used-styles/commit/3fdefdc74ff2baa816c551e5b74e218c9d5701bb#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L37

Let me know if I am missing anything or if you would like a PR to fix it.

**Comment by theKashey** [comment]
Got you. It's no longer listed in files and thus not exported to npm

**Comment by theKashey** [comment]
Verification - https://unpkg.com/browse/used-styles@2.6.1/moveStyles.js
