### ISSUE TITLE
Improve and extend Examples

### ISSUE THREAD

**Issue by Ibadichan** [theKashey/used-styles#63]
Simplify streaming 
https://github.com/theKashey/used-styles/pull/62

**Comment by Ibadichan** [comment]
https://github.com/theKashey/used-styles/pull/62

**Comment by Ibadichan** [comment]
I can create also react + vite + ssr streaming full working template.

**Comment by theKashey** [comment]
That would be more than appreciated and I obviously cannot handle everything by my own

**Comment by Ibadichan** [comment]
ok, i will try to create example a little bit later

**Comment by Ibadichan** [comment]
Hi @theKashey , can you check new demo?
https://github.com/theKashey/used-styles/pull/64

**Comment by theKashey** [comment]
Better that I ever imagined
